//! FactSheet — the deterministic ground-truth layer (spec §4.7 / §5.2).
//!
//! Distillation may only cite facts that appear here; a post-distill verify gate
//! (`omniproj-distill::verify`) checks the model's output against this whitelist and
//! flags anything it can't ground. The point: facts (commit hashes, numbers,
//! paths) are NOT generated by the model — they are injected as data and checked
//! by code. Prompt rules alone proved unenforceable (DeepSeek invented commit
//! `b87d023` despite an explicit "never fabricate" rule).
//!
//! v1 scope is the proven failure mode: fabricated commit hashes. Number/path
//! grounding hooks land on these same types later.

/// Verified facts about a project, produced by capture (no LLM).
#[derive(Debug, Clone, Default)]
pub struct FactSheet {
    /// `None` for non-git projects (then nothing hash-shaped is vouched for).
    pub git: Option<GitFacts>,
}

/// Real git facts. `commit_hashes` are full 40-char SHAs — the whitelist the
/// verify gate matches candidate hashes against (by prefix, so short hashes match).
/// `file_paths` are repo-relative tracked/changed paths — the whitelist path-shaped
/// tokens in distilled output are checked against (spec §5.2 "hash/数字/路径").
#[derive(Debug, Clone, Default)]
pub struct GitFacts {
    pub branch: String,
    pub head_short: String,
    pub commit_hashes: Vec<String>,
    pub file_paths: Vec<String>,
}

impl FactSheet {
    /// Does the substrate vouch for this commit-hash-shaped token? A candidate is
    /// known if it is a prefix of (or equal to) any real commit SHA, case-
    /// insensitively. With no git facts, nothing is known — so every hash-shaped
    /// token in the output gets flagged (a no-git briefing should cite no hashes).
    pub fn knows_hash(&self, candidate: &str) -> bool {
        if candidate.is_empty() {
            return false;
        }
        let cand = candidate.to_ascii_lowercase();
        match &self.git {
            Some(g) => g
                .commit_hashes
                .iter()
                .any(|h| h.to_ascii_lowercase().starts_with(&cand)),
            None => false,
        }
    }

    /// Does the substrate vouch for this path-shaped token? Matches a whitelist
    /// entry exactly, or as a suffix on a path-segment boundary (a briefing may cite
    /// `src/lib.rs` for `crates/foo/src/lib.rs`). With no git facts there is no
    /// whitelist, so the path gate is a no-op (callers must not flag then — unlike
    /// hashes, plain projects legitimately mention files we can't enumerate).
    pub fn knows_path(&self, candidate: &str) -> bool {
        let cand = candidate.trim_matches('/');
        if cand.is_empty() {
            return false;
        }
        match &self.git {
            Some(g) => g
                .file_paths
                .iter()
                .any(|p| p == cand || p.ends_with(&format!("/{cand}"))),
            None => false,
        }
    }

    /// Whether path verification is meaningful (a non-empty whitelist exists).
    pub fn has_path_whitelist(&self) -> bool {
        self.git.as_ref().is_some_and(|g| !g.file_paths.is_empty())
    }

    pub fn has_git(&self) -> bool {
        self.git.is_some()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sheet(hashes: &[&str]) -> FactSheet {
        FactSheet {
            git: Some(GitFacts {
                branch: "main".into(),
                head_short: hashes
                    .first()
                    .map(|h| h[..7].to_string())
                    .unwrap_or_default(),
                commit_hashes: hashes.iter().map(|s| s.to_string()).collect(),
                file_paths: vec!["crates/foo/src/lib.rs".into(), "README.md".into()],
            }),
        }
    }

    #[test]
    fn knows_short_prefix_of_real_hash() {
        let fs = sheet(&["0d906c3f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d"]);
        assert!(fs.knows_hash("0d906c3")); // short hash is a prefix of the full SHA
        assert!(fs.knows_hash("0D906C3")); // case-insensitive
        assert!(fs.knows_hash("0d906c3f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d")); // full
    }

    #[test]
    fn rejects_fabricated_hash() {
        let fs = sheet(&["0d906c3f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d"]);
        assert!(!fs.knows_hash("b87d023")); // the real-world DeepSeek fabrication
    }

    #[test]
    fn no_git_knows_nothing() {
        let fs = FactSheet::default();
        assert!(!fs.has_git());
        assert!(!fs.knows_hash("0d906c3"));
        assert!(!fs.knows_path("src/lib.rs"));
        assert!(!fs.has_path_whitelist());
    }

    #[test]
    fn knows_path_exact_and_segment_suffix() {
        let fs = sheet(&["0d906c3f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d"]);
        assert!(fs.knows_path("crates/foo/src/lib.rs")); // exact
        assert!(fs.knows_path("src/lib.rs")); // suffix on a segment boundary
        assert!(fs.knows_path("lib.rs")); // last segment
        assert!(fs.knows_path("README.md"));
        assert!(!fs.knows_path("b.rs")); // not a segment ("lib.rs" must not match it)
        assert!(!fs.knows_path("src/fake.rs")); // fabricated
        assert!(fs.has_path_whitelist());
    }
}
